name: validate

on:
  pull_request:
    branches:
      - master
      - v*.*

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Test branch name
        if: contains(github.head_ref, '.') # Is version branch
        run: echo "Cannot PR version branch into master or any other version branch"; exit 1
